# Generated by Django 5.1 on 2024-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidadpersonas',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='edad',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_hermanos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-02 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='foto_paciente',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_carnet/'),
        ),
    ]
