# Generated by Django 5.1 on 2024-12-02 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_reserva_cantidadpersonas_remove_reserva_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observaciones',
            field=models.TextField(max_length=5000),
        ),
    ]
